version: 0.2

env: 
  parameter-store:
      image_repo: /dev/ecs/tradechamp/ecr_repository
      
phases:

  install:

          
    commands: 
       - echo Pre-Build started on `date`
       - java -version # Verify the Java version
    

  build:
    commands:
      - echo Build started on `date`
      - java -version
      - javac -version  
      - mvn clean package -Dmaven.test.skip=true
      - echo Build Ended on `date`

  post_build:
     commands:
       - echo bucket name is $BUCKET_NAME
       - pwd 
       - ls -lrt target 
       - cp target/tradechamp-1.0.0.jar codedeploy 
       - ls -lrt codedeploy
            
       # zipping is causing the issue during codedeploy 
       # - cd codedeploy && zip -r ../tradechamp.zip * 
       # 
       - pwd 
       - ls -lrt
            
       # Create an image and push to ECR 
       - echo image repo $image_repo
       - accountID=`aws sts get-caller-identity --query Account --output text`
       - echo accountID = $accountID
       - echo aws region = $AWS_REGION 
       - echo account ID prefix value = $accountId.dkr.ecr.us-east-1.amazonaws.com 
       - postfix="dkr.ecr.us-east-1.amazonaws.com"
       - accountName=$accountID.$postfix
       - echo accountName = $accountName 
       - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $accountName 
       - pwd
         # - commitId=`git log --format="%H" -n 1`
       # get current timestamp and create tag 
       - commitId=`date +"%Y-%m-%d-%H-%M-%S-%3N"`
            
       - echo commitID is $commitId
       - docker build -t $image_repo:$commitId .
       - docker tag  $image_repo:$commitId $image_repo:latest
       - docker push $image_repo:$commitId
       - docker push $image_repo:latest
       
       - docker images 

       # Create a new file "imagedefinitions.json" 
       - echo Writing image definitions file...
       - printf '[{"name":"tradechamp","imageUri":"%s"}]' $image_repo:latest> imagedefinitions.json 
       - cat imagedefinitions.json

            
     artifacts:
        files: 
           - imagedefinitions.json
           - appspec.yml
        
     reports: 
        SureFireReports:
          files:
            - '**/*'
          base-directory: 'target/surefire-reports'
