version: 0.2

phases:

  install:

    commands:
      - echo Pre-Build started on `date`

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -Dmaven.test.skip=true
      - echo Build Ended on `date`

  post_build:
     commands:
       - echo bucket name is $BUCKET_NAME
       - ls -lrt target 
       - cp target/tradechamp-0.0.1-SNAPSHOT.jar codedeploy 
       - ls -lrt codedeploy
            
       # zipping is causing the issue during codedeploy 
       # - cd codedeploy && zip -r ../springdemo2.zip * 
       # 
       - pwd 
       - ls -lrt
            
       # Create an image and push to ECR 
       - echo image repo $springdemo_image_repo
       - accountID=`aws sts get-caller-identity --query Account --output text`
       - echo accountID = $accountID
       - echo aws region = $AWS_REGION 
       - echo account ID prefix value = $accountId.dkr.ecr.us-east-1.amazonaws.com 
       - postfix="dkr.ecr.us-east-1.amazonaws.com"
       - accountName=$accountID.$postfix
       - echo accountName = $accountName 
       - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $accountName 
       - commitId=`git log --format="%H" -n 1`
            
       - echo commitID is $commitId
       - docker build -t $springdemo_image_repo:$commitId .
       - docker push $springdemo_image_repo:$commitId
       - docker images 
            
     artifacts:
        files:
          - '**/*'
        base-directory: codedeploy 
        discard-paths: false  
        
     reports: 
        SureFireReports:
          files:
            - '**/*'
          base-directory: 'target/surefire-reports'
